/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TestnetRouteImport } from './routes/testnet'
import { Route as StewardshipRouteImport } from './routes/stewardship'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as BlockfrostHealthRouteImport } from './routes/blockfrost-health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeIndexRouteImport } from './routes/upgrade.index'
import { Route as UpgradeReturnRouteImport } from './routes/upgrade.return'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as GovernanceNewRouteImport } from './routes/governance.new'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicBlockfrostWebhookRouteImport } from './routes/api/public/blockfrost/webhook'

const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TestnetRoute = TestnetRouteImport.update({
  id: '/testnet',
  path: '/testnet',
  getParentRoute: () => rootRouteImport,
} as any)
const StewardshipRoute = StewardshipRouteImport.update({
  id: '/stewardship',
  path: '/stewardship',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockfrostHealthRoute = BlockfrostHealthRouteImport.update({
  id: '/blockfrost-health',
  path: '/blockfrost-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeIndexRoute = UpgradeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpgradeRoute,
} as any)
const UpgradeReturnRoute = UpgradeReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => UpgradeRoute,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const GovernanceNewRoute = GovernanceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GovernanceRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlockfrostWebhookRoute =
  ApiPublicBlockfrostWebhookRouteImport.update({
    id: '/api/public/blockfrost/webhook',
    path: '/api/public/blockfrost/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blockfrost-health': typeof BlockfrostHealthRoute
  '/developers': typeof DevelopersRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mcp': typeof McpRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stewardship': typeof StewardshipRoute
  '/testnet': typeof TestnetRoute
  '/upgrade': typeof UpgradeRouteWithChildren
  '/yield': typeof YieldRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/governance/new': typeof GovernanceNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/upgrade/return': typeof UpgradeReturnRoute
  '/upgrade/': typeof UpgradeIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/blockfrost/webhook': typeof ApiPublicBlockfrostWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blockfrost-health': typeof BlockfrostHealthRoute
  '/developers': typeof DevelopersRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mcp': typeof McpRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stewardship': typeof StewardshipRoute
  '/testnet': typeof TestnetRoute
  '/yield': typeof YieldRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/governance/new': typeof GovernanceNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/upgrade/return': typeof UpgradeReturnRoute
  '/upgrade': typeof UpgradeIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/blockfrost/webhook': typeof ApiPublicBlockfrostWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blockfrost-health': typeof BlockfrostHealthRoute
  '/developers': typeof DevelopersRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mcp': typeof McpRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stewardship': typeof StewardshipRoute
  '/testnet': typeof TestnetRoute
  '/upgrade': typeof UpgradeRouteWithChildren
  '/yield': typeof YieldRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/governance/new': typeof GovernanceNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/upgrade/return': typeof UpgradeReturnRoute
  '/upgrade/': typeof UpgradeIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/blockfrost/webhook': typeof ApiPublicBlockfrostWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blockfrost-health'
    | '/developers'
    | '/governance'
    | '/marketplace'
    | '/mcp'
    | '/security'
    | '/sitemap.xml'
    | '/stewardship'
    | '/testnet'
    | '/upgrade'
    | '/yield'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/governance/new'
    | '/marketplace/$id'
    | '/upgrade/return'
    | '/upgrade/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/blockfrost/webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blockfrost-health'
    | '/developers'
    | '/governance'
    | '/marketplace'
    | '/mcp'
    | '/security'
    | '/sitemap.xml'
    | '/stewardship'
    | '/testnet'
    | '/yield'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/governance/new'
    | '/marketplace/$id'
    | '/upgrade/return'
    | '/upgrade'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/blockfrost/webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/blockfrost-health'
    | '/developers'
    | '/governance'
    | '/marketplace'
    | '/mcp'
    | '/security'
    | '/sitemap.xml'
    | '/stewardship'
    | '/testnet'
    | '/upgrade'
    | '/yield'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/governance/new'
    | '/marketplace/$id'
    | '/upgrade/return'
    | '/upgrade/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/blockfrost/webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockfrostHealthRoute: typeof BlockfrostHealthRoute
  DevelopersRoute: typeof DevelopersRoute
  GovernanceRoute: typeof GovernanceRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  McpRoute: typeof McpRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StewardshipRoute: typeof StewardshipRoute
  TestnetRoute: typeof TestnetRoute
  UpgradeRoute: typeof UpgradeRouteWithChildren
  YieldRoute: typeof YieldRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBlockfrostWebhookRoute: typeof ApiPublicBlockfrostWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testnet': {
      id: '/testnet'
      path: '/testnet'
      fullPath: '/testnet'
      preLoaderRoute: typeof TestnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stewardship': {
      id: '/stewardship'
      path: '/stewardship'
      fullPath: '/stewardship'
      preLoaderRoute: typeof StewardshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blockfrost-health': {
      id: '/blockfrost-health'
      path: '/blockfrost-health'
      fullPath: '/blockfrost-health'
      preLoaderRoute: typeof BlockfrostHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade/': {
      id: '/upgrade/'
      path: '/'
      fullPath: '/upgrade/'
      preLoaderRoute: typeof UpgradeIndexRouteImport
      parentRoute: typeof UpgradeRoute
    }
    '/upgrade/return': {
      id: '/upgrade/return'
      path: '/return'
      fullPath: '/upgrade/return'
      preLoaderRoute: typeof UpgradeReturnRouteImport
      parentRoute: typeof UpgradeRoute
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/governance/new': {
      id: '/governance/new'
      path: '/new'
      fullPath: '/governance/new'
      preLoaderRoute: typeof GovernanceNewRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blockfrost/webhook': {
      id: '/api/public/blockfrost/webhook'
      path: '/api/public/blockfrost/webhook'
      fullPath: '/api/public/blockfrost/webhook'
      preLoaderRoute: typeof ApiPublicBlockfrostWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GovernanceRouteChildren {
  GovernanceNewRoute: typeof GovernanceNewRoute
}

const GovernanceRouteChildren: GovernanceRouteChildren = {
  GovernanceNewRoute: GovernanceNewRoute,
}

const GovernanceRouteWithChildren = GovernanceRoute._addFileChildren(
  GovernanceRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface UpgradeRouteChildren {
  UpgradeReturnRoute: typeof UpgradeReturnRoute
  UpgradeIndexRoute: typeof UpgradeIndexRoute
}

const UpgradeRouteChildren: UpgradeRouteChildren = {
  UpgradeReturnRoute: UpgradeReturnRoute,
  UpgradeIndexRoute: UpgradeIndexRoute,
}

const UpgradeRouteWithChildren =
  UpgradeRoute._addFileChildren(UpgradeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockfrostHealthRoute: BlockfrostHealthRoute,
  DevelopersRoute: DevelopersRoute,
  GovernanceRoute: GovernanceRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  McpRoute: McpRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StewardshipRoute: StewardshipRoute,
  TestnetRoute: TestnetRoute,
  UpgradeRoute: UpgradeRouteWithChildren,
  YieldRoute: YieldRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBlockfrostWebhookRoute: ApiPublicBlockfrostWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
